//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhanMemBaiGiuXeDAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OCS8BFD\\SQLEXPRESS;Initial Catalog=QL_BaiGiuXe;User ID=sa;Pas" +
            "sword=123")]
        public string QL_BaiGiuXeConnectionString {
            get {
                return ((string)(this["QL_BaiGiuXeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8O63SGA\\SQLEXPRESS;Initial Catalog=QL_HeThongBaiGiuXe;Integra" +
            "ted Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string QL_HeThongBaiGiuXeConnectionString {
            get {
                return ((string)(this["QL_HeThongBaiGiuXeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8O63SGA\\SQLEXPRESS;Initial Catalog=QL_BaiGiuXe;Integrated Sec" +
            "urity=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string QL_BaiGiuXeConnectionString1 {
            get {
                return ((string)(this["QL_BaiGiuXeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-OCS8BFD\\SQLEXPRESS;Initial Catalog=QL_HeThongBaiGiuXe;User ID" +
            "=sa;Password=123")]
        public string QL_HeThongBaiGiuXeConnectionString1 {
            get {
                return ((string)(this["QL_HeThongBaiGiuXeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-5HAB20B;Initial Catalog=QL_HeThongBaiGiuXe;Integrated Securit" +
            "y=True")]
        public string QL_HeThongBaiGiuXeConnectionString2 {
            get {
                return ((string)(this["QL_HeThongBaiGiuXeConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-8O63SGA\\SQLEXPRESS;Initial Catalog=QL_HeThongBaiGiuXe;Integra" +
            "ted Security=True")]
        public string QL_HeThongBaiGiuXeConnectionString3 {
            get {
                return ((string)(this["QL_HeThongBaiGiuXeConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-DSO8J3OR\\SQLEXPRESS;Initial Catalog=QL_HeThongBaiGiuXe;Persist" +
            " Security Info=True;User ID=sa;Password=123")]
        public string QL_HeThongBaiGiuXeConnectionString4 {
            get {
                return ((string)(this["QL_HeThongBaiGiuXeConnectionString4"]));
            }
        }
    }
}
