<?xml version="1.0" encoding="utf-8"?><Database Name="QL_BaiGiuXe" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-OCS8BFD\SQLEXPRESS;Initial Catalog=QL_BaiGiuXe;User ID=sa" SettingsObjectName="DA_PhanMemBaiGiuXe.Properties.Settings" SettingsPropertyName="QL_BaiGiuXeConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BangThe" Member="BangThes">
    <Type Name="BangThe">
      <Column Name="MaThe" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="BangThe_QuetXe" Member="QuetXes" ThisKey="MaThe" OtherKey="IDThe" Type="QuetXe" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTK" Member="LoaiTKs">
    <Type Name="LoaiTK">
      <Column Name="MaCV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LoaiTK_Login" Member="Logins" ThisKey="MaCV" OtherKey="MaCV" Type="Login" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="Username" Type="System.String" DbType="Char(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="LoaiTK_Login" Member="LoaiTK" ThisKey="MaCV" OtherKey="MaCV" Type="LoaiTK" IsForeignKey="true" />
      <Association Name="NhanVien_Login" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="NhanVien_Login" Member="Logins" ThisKey="MaNV" OtherKey="MaNV" Type="Login" />
    </Type>
  </Table>
  <Table Name="dbo.QuetXe" Member="QuetXes">
    <Type Name="QuetXe">
      <Column Name="IDThe" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BIENSO" Type="System.String" DbType="NVarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AnhThe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="BangThe_QuetXe" Member="BangThe" ThisKey="IDThe" OtherKey="MaThe" Type="BangThe" IsForeignKey="true" />
    </Type>
  </Table>
</Database>