<?xml version="1.0" encoding="utf-8"?><Database Name="QL_HeThongBaiGiuXe" Class="DataClassesHTBGXDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-H0R3HLD\SQLEXPRESS;Initial Catalog=QL_HeThongBaiGiuXe;User ID=sa" SettingsObjectName="PhanMemBaiGiuXeDAL.Properties.Settings" SettingsPropertyName="QL_HeThongBaiGiuXeConnectionString6" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TheXe" Member="TheXes">
    <Type Name="TheXe">
      <Column Name="MaThe" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="TheXe_GiaoTac" Member="GiaoTacs" ThisKey="MaThe" OtherKey="MaThe" Type="GiaoTac" />
      <Association Name="TheXe_QuanLyTheXe" Member="QuanLyTheXes" ThisKey="MaThe" OtherKey="MaThe" Type="QuanLyTheXe" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(51)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="NVarChar(21)" CanBeNull="true" />
      <Association Name="NhanVien_TaiKhoan" Member="TaiKhoans" ThisKey="MaNV" OtherKey="MaNV" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiGiaoTac" Member="LoaiGiaoTacs">
    <Type Name="LoaiGiaoTac">
      <Column Name="MaGiaoTac" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenGiaoTac" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LoaiGiaoTac_GiaoTac" Member="GiaoTacs" ThisKey="MaGiaoTac" OtherKey="MaLoaiGiaoTac" Type="GiaoTac" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BienSo" Type="System.String" DbType="NVarChar(21)" CanBeNull="true" />
      <Association Name="KhachHang_GiaoTac" Member="GiaoTacs" ThisKey="MaKH" OtherKey="MaKH" Type="GiaoTac" />
      <Association Name="KhachHang_NgoaiLe" Member="NgoaiLes" ThisKey="MaKH" OtherKey="MaKH" Type="NgoaiLe" />
    </Type>
  </Table>
  <Table Name="dbo.GiaoTac" Member="GiaoTacs">
    <Type Name="GiaoTac">
      <Column Name="MaGiaoTac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaThe" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TenTaiKhoan" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaLoaiGiaoTac" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiGIan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="KhachHang_GiaoTac" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="LoaiGiaoTac_GiaoTac" Member="LoaiGiaoTac" ThisKey="MaLoaiGiaoTac" OtherKey="MaGiaoTac" Type="LoaiGiaoTac" IsForeignKey="true" />
      <Association Name="TheXe_GiaoTac" Member="TheXe" ThisKey="MaThe" OtherKey="MaThe" Type="TheXe" IsForeignKey="true" />
      <Association Name="TaiKhoan_GiaoTac" Member="TaiKhoan" ThisKey="TenTaiKhoan" OtherKey="TenTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DangNhap" Member="DangNhaps">
    <Type Name="DangNhap">
      <Column Name="TenTaiKhoan" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianDangNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThoiGianDangXuat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IDDN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="TaiKhoan_DangNhap" Member="TaiKhoan" ThisKey="TenTaiKhoan" OtherKey="TenTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NgoaiLe" Member="NgoaiLes">
    <Type Name="NgoaiLe">
      <Column Name="MaNL" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTenKH" Type="System.String" DbType="NVarChar(51)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(21)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(51)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(21)" CanBeNull="true" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(51) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(51)" CanBeNull="true" />
      <Association Name="KhachHang_NgoaiLe" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiTK" Member="LoaiTKs">
    <Type Name="LoaiTK">
      <Column Name="MaLoai" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="LoaiTK_TaiKhoan" Member="TaiKhoans" ThisKey="MaLoai" OtherKey="LoaiTaiKhoan" Type="TaiKhoan" />
    </Type>
  </Table>
  <Table Name="dbo.QuanLyTheXe" Member="QuanLyTheXes">
    <Type Name="QuanLyTheXe">
      <Column Name="IDQLy" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTaiKhoan" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="MaThe" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianXuLy" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="TheXe_QuanLyTheXe" Member="TheXe" ThisKey="MaThe" OtherKey="MaThe" Type="TheXe" IsForeignKey="true" />
      <Association Name="TaiKhoan_QuanLyTheXe" Member="TaiKhoan" ThisKey="TenTaiKhoan" OtherKey="TenTaiKhoan" Type="TaiKhoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenTaiKhoan" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="NgayTaoTaiKhoan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LoaiTaiKhoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TaiKhoan_GiaoTac" Member="GiaoTacs" ThisKey="TenTaiKhoan" OtherKey="TenTaiKhoan" Type="GiaoTac" />
      <Association Name="TaiKhoan_DangNhap" Member="DangNhaps" ThisKey="TenTaiKhoan" OtherKey="TenTaiKhoan" Type="DangNhap" />
      <Association Name="TaiKhoan_QuanLyTheXe" Member="QuanLyTheXes" ThisKey="TenTaiKhoan" OtherKey="TenTaiKhoan" Type="QuanLyTheXe" />
      <Association Name="LoaiTK_TaiKhoan" Member="LoaiTK" ThisKey="LoaiTaiKhoan" OtherKey="MaLoai" Type="LoaiTK" IsForeignKey="true" />
      <Association Name="NhanVien_TaiKhoan" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
</Database>